Check 3 keys for password

diff --git a/git-credential-pass b/git-credential-pass
--- a/git-credential-pass
+++ b/git-credential-pass
@@ -7,12 +7,14 @@
 # 2. git config --global credential.helper pass
 
 declare -A attrib
-command -v pass >/dev/null 2>&1 || exit
+if ! command -v pass >/dev/null 2>&1; then
+    echo "Couldn't find command pass" >&2
+    exit
+fi
 
-if [[ $1 = "get" ]]; then
+if [[ $1 = get ]]; then
 	read line
 	while [[ -n "$line" ]]; do
-	    echo "Read stdin: $line" >/dev/stderr
 		key=${line%%=*}
 		value=${line#*=}
 		if [[ $key = "path" ]]; then
@@ -23,19 +25,30 @@ if [[ $1 = "get" ]]; then
 		read line
 	done
 
-	if [[ ${attrib['protocol']} != "https" ]]; then
+	if [[ ${attrib[protocol]} != "https" ]]; then
 		exit
 	fi
 
-	if [ -z "${attrib["host"]}" ]; then
+	if [[ -z "${attrib[host]}" ]]; then
 		exit
 	fi
+	
+	if [[ -z "${attrib[username]}" ]]; then
+	    attrib[username]=git
+	fi
 
-    echo "Looking for '${attrib[username]}@${attrib[host]}/${attrib[path]}'" >/dev/stderr
-    pass=$(pass show "${attrib[username]}@${attrib[host]}/${attrib[path]}")
+    for key in "${attrib[username]}@${attrib[host]}/${attrib[path]}" \
+               "${attrib[username]}@${attrib[host]}" \
+               "${attrib[host]}"; do
+        pass=$(pass show "$key" 2>/dev/null)
+        
+        if [[ -n "$pass" ]]; then
+            break
+        fi
+    done
 
 	if [[ -z "$pass" ]]; then
-		echo "Couldn't find host in pass storage." >/dev/stderr
+		echo "Couldn't find host in pass storage." >&2
 		exit
 	fi
 
