Set default username to the login name

diff --git a/git-credential-pass b/git-credential-pass
--- a/git-credential-pass
+++ b/git-credential-pass
@@ -13,45 +13,46 @@ if ! command -v pass >/dev/null 2>&1; then
 fi
 
 if [[ $1 = get ]]; then
-	read line
-	while [[ -n "$line" ]]; do
-		key=${line%%=*}
-		value=${line#*=}
-		if [[ $key = "path" ]]; then
+    read line
+    while [[ -n "$line" ]]; do
+        key=${line%%=*}
+        value=${line#*=}
+        if [[ $key = "path" ]]; then
             attrib[$key]=${value%.git}
         else
             attrib[$key]=$value
         fi
-		read line
-	done
+        read line
+    done
 
-	if [[ ${attrib[protocol]} != "https" ]]; then
-		exit
-	fi
+    if [[ ${attrib[protocol]} != "https" ]]; then
+        exit
+    fi
 
-	if [[ -z "${attrib[host]}" ]]; then
-		exit
-	fi
-	
-	if [[ -z "${attrib[username]}" ]]; then
-	    attrib[username]=git
-	fi
+    if [[ -z "${attrib[host]}" ]]; then
+        exit
+    fi
+
+    if [[ -z "${attrib[username]}" ]]; then
+        attrib[username]=$(id -nu)
+    fi
 
     for key in "${attrib[username]}@${attrib[host]}/${attrib[path]}" \
                "${attrib[username]}@${attrib[host]}" \
+               "${attrib[host]}/${attrib[path]}" \
                "${attrib[host]}"; do
         pass=$(pass show "$key" 2>/dev/null)
-        
+
         if [[ -n "$pass" ]]; then
             break
         fi
     done
 
-	if [[ -z "$pass" ]]; then
-		echo "Couldn't find host in pass storage." >&2
-		exit
-	fi
+    if [[ -z "$pass" ]]; then
+        echo "Couldn't find host in pass storage." >&2
+        exit
+    fi
 
-	echo username="${attrib["username"]}"
-	echo password="$pass"
+    echo username="${attrib["username"]}"
+    echo password="$pass"
 fi
